"""empty message

Revision ID: ab4ffe6bbfe8
Revises: de024e15bf04
Create Date: 2022-06-03 15:32:21.883829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4ffe6bbfe8'
down_revision = 'de024e15bf04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('created_date', sa.DateTime(), nullable=False))
    op.add_column('venues', sa.Column('created_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'created_date')
    op.drop_column('artists', 'created_date')
    # ### end Alembic commands ###
