"""empty message

Revision ID: f4cd6b70083b
Revises: c4cc831b9622
Create Date: 2022-06-03 20:27:28.474508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4cd6b70083b'
down_revision = 'c4cc831b9622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'created_date')
    op.drop_column('venues', 'created_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('artists', sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
